name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      VITE_S3_BUCKET: ${{ secrets.S3_BUCKET }}
      AWS_IAM_ARN: ${{ secrets.AWS_IAM_ARN }}
      TOOLKIT_STACK: CDKToolkit-poll-position
      STACK_NAME: PollPositionUIStack
      BOOTSTRAP_QUALIFIER: pollpstn
      ECR_REPO: poll-position-ui
      IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/poll-position-ui:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # --- Frontend ---
      - name: Debug VITE_S3_BUCKET
        run: echo "📦 VITE_S3_BUCKET = $VITE_S3_BUCKET"

      - name: Install frontend dependencies
        working-directory: app
        run: npm install

      - name: Build frontend Docker image (inject VITE_S3_BUCKET)
        working-directory: app
        run: |
          docker build \
            --build-arg VITE_S3_BUCKET=$VITE_S3_BUCKET \
            -t $ECR_REPO \
            -f Dockerfile .

      - name: Authenticate Docker with ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      - name: Ensure ECR Repository Exists
        run: |
          aws ecr describe-repositories --repository-names $ECR_REPO --region $AWS_REGION || \
          aws ecr create-repository --repository-name $ECR_REPO --region $AWS_REGION

      - name: Push frontend Docker image to ECR
        run: |
          docker tag $ECR_REPO:latest $IMAGE_URI
          docker push $IMAGE_URI

      # --- Infra ---
      - name: Install CDK dependencies
        working-directory: infra
        run: npm install

      - name: List CDK Stacks (for debug)
        working-directory: infra
        run: npx cdk ls

      - name: Validate CDK Bootstrap Qualifier
        run: |
          ACTUAL_QUALIFIER=$(aws cloudformation describe-stacks \
            --stack-name $TOOLKIT_STACK \
            --region $AWS_REGION \
            --query "Stacks[0].Parameters[?ParameterKey=='Qualifier'].ParameterValue" \
            --output text)

          echo "✅ Found bootstrap qualifier: $ACTUAL_QUALIFIER"

          if [ "$ACTUAL_QUALIFIER" != "$BOOTSTRAP_QUALIFIER" ]; then
            echo "❌ Mismatch: expected '$BOOTSTRAP_QUALIFIER' but found '$ACTUAL_QUALIFIER'"
            exit 1
          fi

      - name: Validate CDK App Configuration
        working-directory: infra
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          ACTUAL=$(jq -r '.app' cdk.json)
          EXPECTED="npx ts-node --prefer-ts-exts bin/poll-position-ui.ts"

          if [[ "$ACTUAL" != "$EXPECTED" ]]; then
            echo "❌ Error: cdk.json 'app' is misconfigured."
            echo "Expected: $EXPECTED"
            echo "Found:    $ACTUAL"
            exit 1
          else
            echo "✅ cdk.json app configuration is correct."
          fi

      - name: Deploy CDK Stack
        working-directory: infra
        run: |
          npx cdk deploy \
            --toolkit-stack-name $TOOLKIT_STACK \
            --context bootstrapQualifier=$BOOTSTRAP_QUALIFIER \
            $STACK_NAME \
            --outputs-file cdk-outputs.json \
            --require-approval never
